site_name: SC Design System
site_url: https://stellantai.github.io/sc/

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - content.code.copy

nav:
  - Home: index.md
  - Design Tokens: tokens.md
  - Responsive Guidelines: responsive-guidelines.md
  - Components: ui/components.md
  - UI:
      - Design: ui/design.md
      - Styles: ui/styles.md
      - Tokens: ui/tokens.md