site_name: SC Design System
site_url: https://stellantai.github.io/sc/

theme:
  name: material

nav:
  - Home: index.md
  - Design Tokens: tokens.md
  - Responsive Guidelines: responsive-guidelines.md
  - Components:
      - Overview: components/index.md